server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/global.yml,classpath:config
  profiles:
    active: native

management:
  security:
    enabled: false